[build]
  publish = "medsim"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/medsim/privacy"
  to = "/medsim/privacy.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
