"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { RocketIcon, SparklesIcon, BrainIcon, CodeIcon, PaletteIcon, StarIcon } from "lucide-react"

interface FeatureCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

export default function Home() {
  const [activeTab, setActiveTab] = useState("ai")

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 bg-gradient-to-b from-background via-primary/5 to-muted">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl w-full space-y-6"
      >
        <motion.div 
          className="text-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
        >
          <Badge variant="secondary" className="font-mono text-sm px-4 py-1">
            100% AI-Generated Platform
          </Badge>
        </motion.div>

        <Card className="shadow-xl border-2">
          <CardHeader className="space-y-1">
            <div className="flex flex-col items-center text-center gap-2">
              <CardTitle className="text-3xl font-bold bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
                Research Polar
              </CardTitle>
              <div className="flex items-center gap-2">
                <p className="text-sm text-muted-foreground">A Project by</p>
                <a 
                  href="https://promptedvisions.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-primary hover:underline font-semibold"
                >
                  PromptedVisions.com
                </a>
              </div>
            </div>
            <Separator className="my-4" />
          </CardHeader>
          
          <CardContent>
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-3 mb-4">
                <TabsTrigger value="ai" className="font-medium">AI Creation</TabsTrigger>
                <TabsTrigger value="features" className="font-medium">AI Features</TabsTrigger>
                <TabsTrigger value="about" className="font-medium">About</TabsTrigger>
              </TabsList>
              
              <TabsContent value="ai" className="space-y-6">
                <div className="text-center space-y-4 py-6">
                  <SparklesIcon className="h-12 w-12 mx-auto text-primary" />
                  <h2 className="text-2xl font-bold">100% AI-Generated Platform</h2>
                  <div className="grid gap-4 md:grid-cols-2 mt-6">
                    <AIFeatureCard
                      icon={<CodeIcon />}
                      title="AI-Written Code"
                      description="Every line of code generated by advanced AI models"
                    />
                    <AIFeatureCard
                      icon={<PaletteIcon />}
                      title="AI Design"
                      description="UI/UX completely designed by artificial intelligence"
                    />
                  </div>
                </div>
              </TabsContent>
              
              <TabsContent value="features" className="space-y-4">
                <div className="grid gap-4 md:grid-cols-2">
                  <FeatureCard 
                    icon={<RocketIcon />}
                    title="AI Analysis"
                    description="Research papers analyzed by machine learning models"
                  />
                  <FeatureCard 
                    icon={<BrainIcon />}
                    title="AI Recommendations"
                    description="Smart content suggestions powered by neural networks"
                  />
                  <FeatureCard 
                    icon={<StarIcon />}
                    title="AI Generation"
                    description="Content and insights automatically generated by AI"
                  />
                </div>
              </TabsContent>
              
              <TabsContent value="about">
                <div className="space-y-4 py-4">
                  <h3 className="font-semibold text-lg text-center">AI-Powered Innovation</h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    Research Polar represents a groundbreaking achievement in AI development. 
                    Every aspect of this platform - from the code architecture to the user interface, 
                    from the content generation to the research analysis - has been created entirely 
                    by artificial intelligence. This project showcases the capabilities of AI in 
                    creating sophisticated research tools, developed in collaboration with PromptedVisions.com.
                  </p>
                </div>
              </TabsContent>
            </Tabs>
          </CardContent>

          <CardFooter className="flex flex-col md:flex-row gap-2 justify-between items-center border-t bg-muted/50 rounded-b-lg p-4">
            <p className="text-xs text-muted-foreground text-center md:text-left">
              100% Created by AI • Powered by Advanced Machine Learning
            </p>
            <div className="flex items-center gap-2">
              <Button 
                variant="ghost" 
                size="sm"
                className="text-xs"
                onClick={() => window.location.href = 'https://promptedvisions.com'}
              >
                Visit PromptedVisions
              </Button>
            </div>
          </CardFooter>
        </Card>
      </motion.div>
    </main>
  )
}

function AIFeatureCard({ icon, title, description }: FeatureCardProps) {
  return (
    <motion.div
      whileHover={{ scale: 1.02 }}
      className="p-4 rounded-lg border bg-card text-card-foreground shadow-sm"
    >
      <div className="flex items-center gap-3">
        <div className="text-primary">{icon}</div>
        <div className="text-left">
          <h3 className="font-semibold">{title}</h3>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
      </div>
    </motion.div>
  )
}

function FeatureCard({ icon, title, description }: FeatureCardProps) {
  return (
    <motion.div
      whileHover={{ scale: 1.02 }}
      className="p-4 rounded-lg border bg-card text-card-foreground shadow-sm"
    >
      <div className="flex items-center gap-3">
        <div className="text-primary">{icon}</div>
        <div>
          <h3 className="font-semibold">{title}</h3>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
      </div>
    </motion.div>
  )
}